services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - HOST=server
      - PORT=7879
    networks:
      - ladder99

  client:
    container_name: client
    build:
      context: .
      dockerfile: client/Dockerfile
    environment:
      - HOST=server
      - PORT=7879
    depends_on:
      server:
        condition: service_started
    networks:
      - ladder99

networks:
  ladder99:
    name: ladder99
