services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - HOST=localhost
      - PORT=7879

  client:
    container_name: client
    build:
      context: .
      dockerfile: client/Dockerfile
    environment:
      - HOST=server
      - PORT=7879
    depends_on:
      server:
        condition: service_started
